# Generated by Django 5.0.6 on 2025-10-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='support_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Level 1 - Basic Support'), (2, 'Level 2 - Technical Support'), (3, 'Level 3 - Expert Support')], help_text='Support level for agents (1-3). Only applicable for support_agent role.', null=True, verbose_name='support level'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('support_agent', 'Support Agent'), ('customer', 'Customer')], db_index=True, default='customer', max_length=20, verbose_name='role'),
        ),
    ]
