# Generated by Django 5.0.6 on 2025-10-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_support_level_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='support_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Level 1 - Basic Support'), (2, 'Level 2 - Technical Support'), (3, 'Level 3 - Expert Support'), (4, 'Level 4 - Senior Expert / Team Lead')], help_text='Support level for agents (1-3). Only applicable for support_agent role.', null=True, verbose_name='support level'),
        ),
    ]
