# Generated by Django 5.0.6 on 2025-10-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_support_level'),
        ('accounts', '0003_user_force_password_change_alter_user_support_level'),
    ]

    operations = [
    ]
