# Generated by Django 5.0.6 on 2025-11-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_address_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, help_text='Last time user was active (for online status)', null=True, verbose_name='last activity'),
        ),
    ]
