# Generated by Django 5.0.6 on 2025-10-20 07:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('content', models.TextField(verbose_name='content')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary of the article', verbose_name='excerpt')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='meta description')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255, verbose_name='keywords')),
                ('views', models.IntegerField(default=0, verbose_name='views')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='helpful votes')),
                ('not_helpful_count', models.IntegerField(default=0, verbose_name='not helpful votes')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('is_public', models.BooleanField(default=True, help_text='Visible to all users including customers', verbose_name='public')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_articles', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles', to='tickets.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'knowledge article',
                'verbose_name_plural': 'knowledge articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
