# Generated by Django 5.0.6 on 2025-10-22 11:48
# Reverted: Changed back to TextField (CKEditor removed, using TinyMCE instead)

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        # No operation needed - keeping content as TextField
        # TextField is the original field type
    ]
