# Generated by Django 5.0.6 on 2025-10-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_alter_knowledgearticle_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgearticle',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
    ]
