# Generated by Django 5.0.6 on 2025-10-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_support_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='support_level',
            field=models.CharField(choices=[('level_1', 'Level 1 - First Line Support'), ('level_2', 'Level 2 - Technical Support'), ('level_3', 'Level 3 - Expert Support'), ('level_4', 'Level 4 - Senior Expert')], db_index=True, default='level_1', max_length=10, verbose_name='support level'),
        ),
    ]
