# Generated by Django 5.0.6 on 2025-10-22 06:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_support_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('equipment_type', models.CharField(blank=True, help_text='e.g., Laptop Cart, Projector Setup, etc.', max_length=100, verbose_name='equipment type')),
                ('serial_number', models.CharField(blank=True, max_length=100, unique=True, verbose_name='serial number')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'mobile classroom',
                'verbose_name_plural': 'mobile classrooms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MobileClassroomLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='location name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'mobile classroom location',
                'verbose_name_plural': 'mobile classroom locations',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='support_level',
            field=models.CharField(choices=[('level_1', 'Level 1 - First Line Support'), ('level_2', 'Level 2 - Technical Support'), ('level_3', 'Level 3 - Expert Support'), ('level_4', 'Level 4 - Senior Expert')], db_index=True, default='level_1', max_length=10, verbose_name='support level'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='mobile_classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.mobileclassroom', verbose_name='mobile classroom'),
        ),
        migrations.AddField(
            model_name='mobileclassroom',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='tickets.mobileclassroomlocation', verbose_name='location'),
        ),
    ]
