# Generated by Django 5.0.6 on 2025-10-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_support_level'),
        ('tickets', '0003_mobileclassroom_mobileclassroomlocation_and_more'),
    ]

    operations = [
    ]
