# Generated by Django 5.0.6 on 2025-11-04 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_mobile_classroom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_from_email',
            field=models.BooleanField(default=False, help_text='Ticket was created from incoming email', verbose_name='created from email'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='email_from',
            field=models.EmailField(blank=True, help_text='Original email sender address', max_length=254, null=True, verbose_name='email from'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='author_email',
            field=models.EmailField(blank=True, help_text='Email for email-based comments', max_length=254, null=True, verbose_name='author email'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='author_name',
            field=models.CharField(blank=True, help_text='Name for email-based comments', max_length=255, null=True, verbose_name='author name'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='is_from_email',
            field=models.BooleanField(default=False, help_text='Comment was created from incoming email', verbose_name='from email'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_comments', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
    ]
