# Generated by Django 5.0.6 on 2025-10-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='license_code',
            field=models.CharField(blank=True, help_text='ABoro-Soft Helpdesk License Code (format: PRODUCT-VERSION-DURATION-EXPIRY-SIGNATURE)', max_length=255, null=True, verbose_name='License Code'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='license_expiry_date',
            field=models.DateField(blank=True, help_text='When the current license expires', null=True, verbose_name='License Expiry Date'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='license_features',
            field=models.JSONField(default=list, help_text='List of enabled features for current license', verbose_name='License Features'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='license_last_validated',
            field=models.DateTimeField(blank=True, help_text='When the license was last validated', null=True, verbose_name='License Last Validated'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='license_max_agents',
            field=models.IntegerField(default=5, help_text='Maximum number of support agents allowed by license', verbose_name='License Max Agents'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='license_product',
            field=models.CharField(choices=[('STARTER', 'Starter (€199/month - 5 agents)'), ('PROFESSIONAL', 'Professional (€499/month - 20 agents)'), ('ENTERPRISE', 'Enterprise (€1,299/month - unlimited)'), ('ON_PREMISE', 'On-Premise (€10,000 one-time)'), ('TRIAL', 'Free Trial (30 days)')], default='TRIAL', help_text='Current license type', max_length=50, verbose_name='License Product'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='license_valid',
            field=models.BooleanField(default=False, help_text='Indicates if the current license is valid', verbose_name='License Valid'),
        ),
    ]
