# Generated by Django 5.0.6 on 2025-11-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='ai_enabled',
            field=models.BooleanField(default=False, help_text='KI-gestützte Antworten im Live Chat aktivieren', verbose_name='AI Chat Support aktiviert'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ai_max_tokens',
            field=models.IntegerField(default=500, help_text='Maximale Länge der KI-Antworten', verbose_name='AI Max Tokens'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ai_provider',
            field=models.CharField(choices=[('chatgpt', 'ChatGPT (OpenAI)'), ('claude', 'Claude (Anthropic)')], default='claude', help_text='Welche KI für automatische Antworten verwenden', max_length=20, verbose_name='AI Provider'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ai_response_delay',
            field=models.IntegerField(default=3, help_text='Wartezeit bevor KI antwortet (um natürlicher zu wirken)', verbose_name='AI Antwort Verzögerung (Sekunden)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='anthropic_api_key',
            field=models.CharField(blank=True, help_text='API Key für Claude Integration (optional, nutzt sonst Free-Version)', max_length=255, null=True, verbose_name='Anthropic API Key'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text='API Key für ChatGPT Integration', max_length=255, null=True, verbose_name='OpenAI API Key'),
        ),
    ]
