# Generated by Django 5.0.6 on 2025-11-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_systemsettings_ai_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='accent_color',
            field=models.CharField(default='#FF6600', help_text='Akzentfarbe für wichtige CTAs', max_length=7, verbose_name='Accent Color'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='border_radius',
            field=models.IntegerField(default=8, help_text='Eckenradius für Cards und Buttons', verbose_name='Border Radius (px)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='danger_color',
            field=models.CharField(default='#CC0000', help_text='Farbe für Warnungen und Fehler', max_length=7, verbose_name='Danger Color'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_dark_mode',
            field=models.BooleanField(default=False, help_text='Dark Mode Umschalter aktivieren', verbose_name='Enable Dark Mode'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='font_family',
            field=models.CharField(choices=[('inter', 'Inter (Modern)'), ('roboto', 'Roboto (Standard)'), ('playfair', 'Playfair (Elegant)'), ('poppins', 'Poppins (Casual)')], default='inter', help_text='Schriftart für die Anwendung', max_length=100, verbose_name='Font Family'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='primary_color',
            field=models.CharField(default='#0066CC', help_text='Primärfarbe für Hauptelemente', max_length=7, verbose_name='Primary Color'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='secondary_color',
            field=models.CharField(default='#00B366', help_text='Sekundärfarbe für Nebenelemente', max_length=7, verbose_name='Secondary Color'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='theme_variant',
            field=models.CharField(choices=[('default', 'Default (Modern Blue)'), ('professional', 'Professional (Dark Blue)'), ('bright', 'Bright (Orange)'), ('custom', 'Custom')], default='default', help_text='Vordefiniertes Theme oder Custom für Admin-Konfiguration', max_length=50, verbose_name='Theme Variant'),
        ),
    ]
