# Generated by Django 5.0.6 on 2025-11-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_systemsettings_accent_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='theme_variant',
            field=models.CharField(choices=[('default', 'Default (Modern Blue)'), ('professional', 'Professional (Dark Blue)'), ('bright', 'Bright (Orange)'), ('modern', 'Modern (Indigo & Teal)'), ('corporate', 'Corporate (Navy Blue)'), ('dark', 'Dark Mode (Dark Gray & Blue)'), ('custom', 'Custom')], default='default', help_text='Vordefiniertes Theme oder Custom für Admin-Konfiguration', max_length=50, verbose_name='Theme Variant'),
        ),
    ]
