# Generated by Django 5.0.6 on 2025-11-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_systemsettings_theme_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='license_expiry_date',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='license_features',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='license_max_agents',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='license_product',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='license_valid',
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='license_code',
            field=models.CharField(blank=True, help_text='ABoro-Soft Helpdesk License Code - alle Features werden automatisch erkannt', max_length=255, null=True, verbose_name='License Code'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='stats_permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Erweiterte Statistik-Berechtigungen (optional, leer lassen falls nicht benötigt)', verbose_name='Statistics Permissions (Optional)'),
        ),
    ]
