# Generated by Django 5.0.6 on 2025-11-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_remove_redundant_license_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='ai_provider',
            field=models.CharField(choices=[('llama3', 'LLAMA3 (Lokal - kostenlos)'), ('chatgpt', 'ChatGPT (OpenAI)'), ('claude', 'Claude (Anthropic)')], default='llama3', help_text='Welche KI für automatische Antworten verwenden', max_length=20, verbose_name='AI Provider'),
        ),
    ]
