# Generated by Django 5.0.6 on 2025-11-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Agent'), ('active', 'Active Chat'), ('escalated', 'Escalated to Agent'), ('ended', 'Chat Ended')], default='waiting', max_length=20),
        ),
    ]
