# Generated by Django 5.0.6 on 2025-11-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsettings',
            name='allowed_domains',
            field=models.TextField(default='https://aboro-it.net,https://www.aboro-it.net', help_text='Comma-separated list of domains allowed to embed the chat widget'),
        ),
    ]
